name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run linters
        uses: tillhainbach/lint-action@v1
        with:
          eslint: true
          eslint_extensions: 'js,jsx,tx,tsx'
          prettier: true
          prettier_extensions: 'js,jsx,tx,tsx,css,md,json,yaml'
          stylelint: true
          stylelint_extensions: 'css,js,jsx,tsx,sass,scss'

  commitlint:
    name: Commit Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
